### PR TITLE
Enhancements/ui fix

### LINKED ISSUE #412: Enhancement / chart  tx fees change to GWEI or Eth
Currently Chart for tx fess on home page is using WEI values. These values are very long, and as a result strings on the chart axis are 200000B. 

So in oder to make it more friendly, change values to GWEI or Eth

### LINKED ISSUE #413: Address Details - UI broken for total txs number
- What is the current behavior?
      
On Address detail's page, total number of transactions card height is bigger then the rest of the card within the group (see picture):

screen shot 2019-03-04 at 6 26 06 pm

 - What is the expected behavior?

All cards should be the same height

### PR DESCRIPTION
**Pull request by olgakup**
This fixes  #412 and fixes #413

This is ready for review

   - Fixed UI in Address Detail Page
   - Changed Values to Eth and GWEI in live chart Tx Fees
   - Fixed Footnotes props names
   - Changed type to TranslateResult in Footnote Prop
   - Added footnote type in live charts: LiveTx, LiveTxFees

### CODE REVIEW

File: apps/explorer/src/core/components/props/index.ts [hunk 1]
```diff
@@ -19,7 +19,7 @@ export interface NavHeader {
 
 export interface Footnote {
   color?: string
-  text?: string
+  text?: TranslateResult
```
Comment (aldoborrero) [inline apps/explorer/src/core/components/props/index.ts]: Be careful with this change as you will affect other components using Footnote (and you're changing only one).

Said that, you can modify Footnote to use the following:

```
export interface Footnote {
  text?: TranslateResult | string
}
```

So it accept both formats and the other components are not affected by this change.

Or the other possibility is to take a look on other components that are using Footnote and change them.

File: apps/explorer/src/modules/addresses/components/AddressDetail.vue [hunk 2]
```diff
@@ -96,6 +96,7 @@ export default class AddressDetail extends Mixins(StringConcatMixin) {
 
   @Prop(Object) account: AccountInfo
 
+  temp = false
```
Comment (aldoborrero) [inline apps/explorer/src/modules/addresses/components/AddressDetail.vue]: Let's try to be strict on the way we organize the source code. So below props we have initial data, which can be formatted with a sectioned comment:

```
/*
  ===================================================================================
    Initial Data
  ===================================================================================
  */

  temp = false
```

Comment (aldoborrero) [reply apps/explorer/src/modules/addresses/components/AddressDetail.vue]: Apart from that is that variable being used? If not, just delete it

File: apps/explorer/src/core/components/props/index.ts (hunk 1 above)
Comment (aldoborrero) [reply apps/explorer/src/core/components/props/index.ts]: I've pushed the change to the other components instead of using toString() method (take a look on my commit)

File: apps/explorer/src/modules/addresses/components/AddressDetail.vue (hunk 2 above)
Comment (olgakup) [reply apps/explorer/src/modules/addresses/components/AddressDetail.vue]: oops that was a temp variable, for testing, i should have deleted it.

Comment (olgakup) [reply apps/explorer/src/modules/addresses/components/AddressDetail.vue]: I will take a look !

File: apps/explorer/src/core/components/props/index.ts (hunk 1 above)
Comment (olgakup) [reply apps/explorer/src/core/components/props/index.ts]: I will take a look at it :)

**Comment by olgakup** [comment]
this should be ready for review again. I got carried away and also checked other props, deleted unused ones etc.

File: apps/explorer/src/core/components/ui/AppTabs.vue [hunk 3]
```diff
@@ -35,7 +35,7 @@ export default class AppTabs extends Vue {
   ===================================================================================
   */
 
-  @Prop(Array) tabs!: Tab[]
+  @Prop(Array) tabs: Tab[]
```
Comment (aldoborrero) [inline apps/explorer/src/core/components/ui/AppTabs.vue]: Re-add the ! (is going to complain on strict: true otherwise)
